version: '2'
services:
    iblogjhipster-app:
        image: iblogjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iblogjhipster-mysql:3306/iblogjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    iblogjhipster-mysql:
        extends:
            file: mysql.yml
            service: iblogjhipster-mysql
